classdef tpv_internpar < handle
    properties
        memorysize = 2; % in GB
        floattype = 'double';
        loaddata = true;
        readdata = true;
        guessspikes = false;
        guessspikesall = false;
        defaultdt = 1; % default frame time if not specified in trial headers
    end
    methods (Static)
        function [s spec] = default
            s = struct( ...
                'fontsize',     9, ...
                'textfontsize', 10, ...
                'memorysize',   2, ...
                'floattype',    'double', ...
                'loaddata',     false, ...
                'seldotrial',   false, ...
                'defaultdt',    1, ...
                'imnav',        'zoom', ...
                'imscroll',     'off', ...
                'tcnav',        'zoom', ...
                'tcscroll',     'off' ...
                );
            spec = struct( ...
                'a',            {'label'        'DISPLAY'}, ...
                'fontsize',     {'stepper 1 4 16 1 %i'  'Controls font size'}, ...
                'textfontsize', {'stepper 1 4 30 1 %i'  'Text font size'}, ...
                'b',            {'label'        'GENERAL BEHAVIOR'}, ...
                'seldotrial',   {'logical'      'Trial-specific selection'}, ...
                'c',            {'label'        'MEMORY SAVING'}, ...
                'memorysize',   {'stepper 1 1 100 1 %i' 'Memory size (GB)'}, ...
                'floattype',    {{'double' 'single'}    'Preffered float type'}, ...
                'loaddata',     {'logical'      'Load data at opening'}, ...
                'd',            {'label'        'DATA HANDLING'}, ...
                'defaultdt',    {'double'       'Default frame time (s)'}, ...
                'e',            {'label'        'NAVIGATION'}, ...
                'imnav',        {{'zoom' 'pan'} 'Image navigation'}, ...
                'imscroll',     {{'off' 'on'}   'Image scroll wheel zooming'}, ...
                'tcnav',        {{'zoom' 'pan'} 'Time courses navigation'}, ...
                'tcscroll',     {{'off' 'x' 'y' 'xy'}   'Time courses scroll wheel zooming'} ...
                );
        end
    end
end